-- MySQL Script generated by MySQL Workbench
-- 09/19/15 21:29:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `vards` VARCHAR(25) NOT NULL,
  `uzvards` VARCHAR(25) NOT NULL,
  `personasKods` VARCHAR(12) NOT NULL,
  `adrese` VARCHAR(50) NOT NULL,
  `pilseta` VARCHAR(20) NOT NULL,
  `foto` LONGBLOB NULL,
  `darbaVieta` VARCHAR(20) NOT NULL,
  `lietotajaLoma` VARCHAR(1) NOT NULL,
  `lietotajvards` VARCHAR(20) NOT NULL,
  `parole` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonaApgutais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonaApgutais` (
  `idPersonaApgutais` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `SertifikatsDiplomsKurss` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPersonaApgutais`, `Persona_idPersona`),
  INDEX `fk_PersonaApgutais_Persona_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_PersonaApgutais_Persona`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kurss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kurss` (
  `idKurss` INT NOT NULL,
  `kursaKods` VARCHAR(10) NOT NULL,
  `kKursaNosaukums` VARCHAR(50) NOT NULL,
  `kursaApraksts` VARCHAR(300) NOT NULL,
  `nepieciesamaisAuditorijasTips` VARCHAR(1) NOT NULL,
  `kMaksimalaisStudentuSkaits` INT NOT NULL,
  `kursaIlgums` INT NOT NULL,
  `kursaDiplomaDokuments` LONGBLOB NULL,
  `kursaProgrammaDokuments` LONGBLOB NULL,
  `kursaMacibuMaterialsDokuments` LONGBLOB NULL,
  PRIMARY KEY (`idKurss`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Auditorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Auditorija` (
  `idAuditorija` INT NOT NULL,
  `atrasanasVieta` VARCHAR(50) NOT NULL,
  `auditorijasTips` VARCHAR(1) NOT NULL,
  `aMaksimalaisStudentuSkaits` INT NOT NULL,
  `tafele` TINYINT(1) NOT NULL,
  `projektors` TINYINT(1) NOT NULL,
  `videoKonference` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idAuditorija`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonaNoslogojums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonaNoslogojums` (
  `idPersonaNoslogojums` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `pDatums` DATE NOT NULL,
  `pLaiksNo` TIME NOT NULL,
  `pLaiksLidz` TIME NOT NULL,
  PRIMARY KEY (`idPersonaNoslogojums`, `Persona_idPersona`),
  INDEX `fk_PersonaNoslogojums_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_PersonaNoslogojums_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AuditorijaNoslogojums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AuditorijaNoslogojums` (
  `idAuditorijaNoslogojums` INT NOT NULL,
  `aDatums` DATE NOT NULL,
  `aLaiksNo` TIME NOT NULL,
  `aLaiksLidz` TIME NOT NULL,
  `Auditorija_idAuditorija` INT NOT NULL,
  PRIMARY KEY (`idAuditorijaNoslogojums`, `Auditorija_idAuditorija`),
  INDEX `fk_AuditorijaNoslogojums_Auditorija1_idx` (`Auditorija_idAuditorija` ASC),
  CONSTRAINT `fk_AuditorijaNoslogojums_Auditorija1`
    FOREIGN KEY (`Auditorija_idAuditorija`)
    REFERENCES `mydb`.`Auditorija` (`idAuditorija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona_has_Kurss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona_has_Kurss` (
  `Persona_idPersona` INT NOT NULL,
  `Kurss_idKurss` INT NOT NULL,
  PRIMARY KEY (`Persona_idPersona`, `Kurss_idKurss`),
  INDEX `fk_Persona_has_Kurss_Kurss1_idx` (`Kurss_idKurss` ASC),
  INDEX `fk_Persona_has_Kurss_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Persona_has_Kurss_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Persona_has_Kurss_Kurss1`
    FOREIGN KEY (`Kurss_idKurss`)
    REFERENCES `mydb`.`Kurss` (`idKurss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kurss_has_Auditorija`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kurss_has_Auditorija` (
  `Kurss_idKurss` INT NOT NULL,
  `Auditorija_idAuditorija` INT NOT NULL,
  PRIMARY KEY (`Kurss_idKurss`, `Auditorija_idAuditorija`),
  INDEX `fk_Kurss_has_Auditorija_Auditorija1_idx` (`Auditorija_idAuditorija` ASC),
  INDEX `fk_Kurss_has_Auditorija_Kurss1_idx` (`Kurss_idKurss` ASC),
  CONSTRAINT `fk_Kurss_has_Auditorija_Kurss1`
    FOREIGN KEY (`Kurss_idKurss`)
    REFERENCES `mydb`.`Kurss` (`idKurss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kurss_has_Auditorija_Auditorija1`
    FOREIGN KEY (`Auditorija_idAuditorija`)
    REFERENCES `mydb`.`Auditorija` (`idAuditorija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PersonaPasniedzamieKursi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PersonaPasniedzamieKursi` (
  `idPersonaPasniedzamieKursi` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  `pKursaNosaukums` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPersonaPasniedzamieKursi`, `Persona_idPersona`),
  INDEX `fk_PersonaPasniedzamieKursi_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_PersonaPasniedzamieKursi_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
